channel_sources:
- freecad/label/dev,conda-forge
channel_targets:
- freecad dev
c_stdlib_version:     # [osx]
  - '11.0'            # [osx and arm64]
  - '10.13'           # [osx and x86_64]
occt:
  - 7.8.1